package com.dcfs.esb.ftp.common.cons;

/**
 * EFS_FILE_SAVE0 用原文件名
 * EFS_FILE_SAVE1 文件重命名
 * EFS_CLIENT_REGISTER 客户端注册
 * EFS_CLIENT_UNREGISTER客户端注销
 * EFS_USER_REGISTER 用户注册
 * EFS_FILE_UPLOAD_CLEAR 文件归档
 * Created by mocg on 2016/7/26.
 */
public enum KfkTopic {
    EFS_FILE_SAVE0, EFS_FILE_SAVE1, EFS_FILE_UPLOAD, EFS_FILE_DOWNLOAD, EFS_FILE_MSGDOWNLOADRESULT, EFS_FILE_DEL, EFS_FILE_DISTRIBUTE, EFS_FILE_DEL_SAME,
    EFS_PUSH_FILE_MSG_2CLI, EFS_NODE_LIST_GET,EFS_CLIENT_REGISTER,EFS_CLIENT_UNREGISTER,EFS_USER_REGISTER,
    EFS_FILE_UPLOAD_CLEAR
}
